Don't pick up kernel from debian backports
iocost-benchmark/resctl-demo-image-recipe pull request #60
Opened 2024-12-03 08:59 UTC by r-c-n

Stay with the kernel from debian bookworm for now, as fetching the backports kernel was making the resctl-demo image unable to boot with this issue:

```
Initramfs unpacking failed: invalid magic at start of compressed archive
```

2024-12-03 09:21 UTC, obbardc requested changes
I think the kernel version from stable is too old to run resctl-demo.

2024-12-03 10:32 UTC, r-c-n commented
The current kernel version in bookworm is 6.1, I tested it, ran a few benchmarks on it just fine. I haven't tested `resctl-demo` itself, though, if you're referring to that precisely.

2025-01-14 19:04 UTC, d4s commented
@obbardc  looks like the issue is installing kernel from main first and re-install it from backports.
Using only the single install from backports do the trick and save a bit of time, please check https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/61

I've added the overlay with preferences configuration for linux-* packages. But I need a suggestion -- probably it would be better to add `--target-release` preference to debos apt action and use it?

The project is new for me, so maybe a dump question  -- why only the kernel is used from backports? Shouldn't be used all packages from backports, including ones added into ospack?

2025-01-14 19:28 UTC, obbardc commented
Sorry, I have little interest in this project now. But your PR looks good.

2025-05-21 09:45 UTC, d4s commented
Closed due https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/61

2025-05-21 09:45 UTC, closed without merging